[template]
include = [
  "package.json.liquid",
  "index.html.liquid",
  "src/main.ts.liquid",
  "src-tauri/Cargo.toml.liquid",
  "src-tauri/tauri.conf.json.liquid",
  "src-tauri/src/main.rs.liquid",
]
